class MyMath {
	int divide(int num1, int num2) {
		int ans = num1/num2;
		return 
	}
}
public class Test {

	public static void main(String[] args) {
		
		int num1 = 10, num2 = 0, num3 = 0;
		int arr[] = {100, 200, 300, 400};
		
//		try {
//			num3 = num1 / num2;
//			System.out.println("Num3" + num3);
//			System.out.println(arr[4]);
//		}catch(ArithmeticException ae) {
//			ae.printStackTrace();
//		}catch(ArrayIndexOutOfBoundsException e) {
//			e.printStackTrace();
//		}catch (Exception e) {//For ALl(For Others)
//			e.printStackTrace();
//		}finally {
//			//close the resources opened in try {}
//			System.out.println("This will get executed whether the exception is raise or not");
//		}
		
		System.out.println("Main End...");
	}

}